<?php

// Constantes liées au code HTTP
define("STATUS_HTTP_OK", 200);
define("STATUS_HTTP_CREATED", 201);
define("STATUS_HTTP_MAUVAISE_REQUETE", 400);
define("STATUS_HTTP_NON_AUTORISE", 401);
define("STATUS_HTTP_INTERDIT", 403);
define("STATUS_HTTP_NON_TROUVE", 404);
define("STATUS_HTTP_METHODE_NON_AUTORISEE", 405);
define("STATUS_HTTP_ERREUR_DU_SERVEUR", 500);